---
abstract: 'a high-level bot framework for interacting with MediaWiki wikis'
author:
  - 'Dan Collins <dcollins@cpan.org>'
  - 'Mike.lifeguard <lifeguard@cpan.org>'
  - 'Alex Rowe <alex.d.rowe@gmail.com>'
  - 'Oleg Alexandrov <oleg.alexandrov@gmail.com>'
  - 'jmax.code <jmax.code@gmail.com>'
  - 'Stefan Petrea <stefan.petrea@gmail.com>'
  - 'kc2aei <kc2aei@gmail.com>'
  - bosborne@alum.mit.edu
  - 'Brian Obio <brianobio@gmail.com>'
  - 'patch and bug report contributors'
build_requires:
  PWP: 0
  Test::More: 0.96
  Test::Warn: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MediaWiki-Bot
requires:
  Carp: 0
  Digest::MD5: 2.39
  Encode: 0
  HTML::Entities: 3.28
  LWP::Protocol::https: 0.57
  MediaWiki::API: 0.35
  Module::Pluggable: 0
  perl: 5.008
resources:
  bugtracker: http://code.google.com/p/perlwikipedia/issues/list
version: 3.3.1_2
