---
abstract: 'a MediaWiki bot framework written in Perl'
author:
  - 'Dan Collins <en.wp.st47@gmail.com>'
  - 'Mike.lifeguard <mike.lifeguard@gmail.com>'
  - 'Alex Rowe <alex.d.rowe@gmail.com>'
  - 'Oleg Alexandrov <oleg.alexandrov@gmail.com>'
  - 'jmax.code <jmax.code@gmail.com>'
  - 'Stefan Petrea <stefan.petrea@gmail.com>'
  - 'kc2aei <kc2aei@gmail.com>'
  - bosborne@alum.mit.edu
  - 'Brian Obio <brianobio@gmail.com>'
  - 'patch and bug report contributors'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102221, CPAN::Meta::Converter version 2.102160'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MediaWiki-Bot
requires:
  Carp: 0
  Crypt::SSLeay: 0.57
  Digest::MD5: 2.39
  Encode: 0
  HTML::Entities: 3.28
  MediaWiki::API: 0.20
  Module::Pluggable: 0
  URI::Escape: 1.35
  WWW::Mechanize: 1.30
  XML::Simple: 2.16
  perl: 5.008
version: 3.2.1
