--- #YAML:1.0
name:                MediaWiki-Bot
version:             3.0.0
abstract:            a Wikipedia bot framework written in Perl
license:             gpl
author:              
    - Perlwikipedia team
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Crypt::SSLeay:                 0.57
    Digest::MD5:                   2.39
    Encode:                        0
    HTML::Entities:                3.28
    MediaWiki::API:                0.2
    Module::Pluggable:             0
    URI::Escape:                   1.35
    WWW::Mechanize:                1.3
    XML::Simple:                   2.16
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
