---
abstract: 'a MediaWiki bot framework written in Perl'
author:
  - 'Dan Collins <en.wp.st47@gmail.com>'
  - 'Mike.lifeguard <mike.lifeguard@gmail.com>'
  - 'Alex Rowe <alex.d.rowe@gmail.com>'
  - 'Oleg Alexandrov <oleg.alexandrov@gmail.com>'
  - 'jmax.code <jmax.code@gmail.com>'
  - 'Brian Obio <brianobio@gmail.com>'
  - 'Stefan Petrea <stefan.petrea@gmail.com>'
  - 'kc2aei <kc2aei@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::Kwalitee: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MediaWiki-Bot
requires:
  Carp: 0
  Digest::MD5: 0
  Encode: 0
  HTML::Entities: 0
  MediaWiki::API: 0
  Module::Pluggable: 0
  URI::Escape: 0
  WWW::Mechanize: 0
  XML::Simple: 0
version: 3.1.6
